/**
 * Squat rep animation — pure frame and timing data.
 *
 * Zero React, zero I/O, zero randomness. Given a load ratio it returns the same
 * frames every time; the tests lean on that.
 *
 * ---------------------------------------------------------------------------
 * THE POINT OF THIS MODULE
 * ---------------------------------------------------------------------------
 * GDD §7.1: "Weight is the whole point — a maximal squat must not animate like
 * a light one." GDD §12.2 sharpens it into the half of the sprite bar that can
 * actually be checked without reference art: does a maximal attempt animate
 * *heavier*, not merely slower?
 *
 * Four things differ, and only the first is duration:
 *
 *   1. Duration. A maximal rep takes longer. Necessary, nowhere near
 *      sufficient, and on its own it is the cheap fake.
 *   2. Velocity SHAPE. The ascent is generated by integrating dt = dh / v(h)
 *      through a velocity notch at the sticking point. A light rep's notch is
 *      shallow and it rises at nearly constant speed; a maximal rep's notch is
 *      deep, so the bar spends a large share of its ticks moving almost not at
 *      all a third of the way up, then finishes. Normalise both reps to the
 *      same duration and they are still different curves. That is the test
 *      that "merely slower" cannot pass.
 *   3. Bar path. Sagittal forward drift peaks at the sticking point and scales
 *      hard with load; frontal-plane lateral shake and bar tilt appear only
 *      under real weight.
 *   4. Pose. Two quantised channels deform the drawing itself — `strainLevel`
 *      and `pitchLevel`. A single still frame from the maximal rep is a
 *      different drawing from the same-depth still frame of the light one,
 *      with timing removed and with the same bar on the shoulders.
 *
 * ---------------------------------------------------------------------------
 * THE VIEW PROBLEM, STATED RATHER THAN GLOSSED
 * ---------------------------------------------------------------------------
 * `barForwardPx` is sagittal — toward the toes. The sprite is a front view (see
 * `rig.ts` for why), so forward drift is NOT drawn as a horizontal offset, and
 * anyone reading a frontal sprite expecting to see 4 px of sideways travel will
 * not find it: the camera cannot see it. What the camera CAN see is the body's
 * share of it — hips back and up, torso folding away from the lens, head
 * craning to fight it — and that is `pitchLevel`, quantised from this value
 * through `pitchLevelForDriftPx` and drawn from PITCH's authored deltas.
 *
 * The raw px figure stays on the sample so a side-on bar-path trace can plot it
 * honestly, and the inspection contact sheet graphs it beside the sprites.
 */

import {
  TICK_MS,
  TIMING,
  QUANTISE,
  BRACE_SETTLE_DEPTH,
  DESCENT,
  STICK,
  BAR_PATH,
  BEND,
  STRAIN,
  CHALK,
  LOAD_PRESETS,
  byLoad,
  ticksByLoad,
  clampLoadRatio,
} from './spriteTuning';
import {
  barYAtDepth,
  pitchLevelForDriftPx,
  strainLevel,
  type RepDirection,
} from './rig';

export type RepPhase = 'BRACE' | 'DESCENT' | 'HOLE' | 'ASCENT' | 'LOCKOUT';

export const REP_PHASES: readonly RepPhase[] = [
  'BRACE',
  'DESCENT',
  'HOLE',
  'ASCENT',
  'LOCKOUT',
];

/** State of the lift on one 60 Hz tick. */
export interface SquatSample {
  readonly tick: number;
  readonly phase: RepPhase;
  readonly direction: RepDirection;
  /** 0 = standing, 1 = bottom of the hole. */
  readonly depth: number;
  /** 1 - depth. Normalised bar height; the velocity model's variable. */
  readonly barHeight: number;
  /** Bar centre-line in sprite px, from the rig's own drawings. */
  readonly barYPx: number;
  /** Sagittal drift toward the toes, px. Not drawn in a front view. */
  readonly barForwardPx: number;
  /** Frontal-plane offset of the bar centre, px. Drawn. */
  readonly barLateralPx: number;
  /** Bar tilt, degrees, positive = lifter's right side high. Drawn. */
  readonly barTiltDeg: number;
  /** Sleeve droop from whip, px. Drawn. */
  readonly barBendPx: number;
  readonly strain: number;
  readonly chalkPuff: number;
}

/** One displayed animation frame: a drawing plus how long it is held. */
export interface SquatFrame {
  readonly index: number;
  readonly startTick: number;
  readonly holdTicks: number;
  readonly phase: RepPhase;
  readonly direction: RepDirection;
  /** Depth quantised to the sheet's authored steps. Identifies the drawing. */
  readonly poseDepth: number;
  readonly strainLevel: number;
  /** Quantised body response to sagittal forward drift. See the header. */
  readonly pitchLevel: number;
  readonly barLateralPx: number;
  readonly barTiltDeg: number;
  readonly barBendPx: number;
  readonly chalkMotes: number;
  /** Un-quantised state at the tick this frame starts on, for data consumers. */
  readonly sample: SquatSample;
}

export interface SquatRep {
  readonly loadRatio: number;
  readonly samples: readonly SquatSample[];
  readonly frames: readonly SquatFrame[];
  readonly totalTicks: number;
  readonly totalMs: number;
  readonly phaseTicks: Readonly<Record<RepPhase, number>>;
}

// ---------------------------------------------------------------------------
// Quantisation of drawn state. A 16-bit game ships a finite sheet; continuous
// per-frame deformation is a modern-engine tell. These say how finite, and they
// are tunables, so they live in spriteTuning.QUANTISE. Re-exported here under
// their working names because this is the module that uses them.
// ---------------------------------------------------------------------------

export const DEPTH_STEPS = QUANTISE.DEPTH_STEPS;
export const TILT_QUANTUM_DEG = QUANTISE.TILT_QUANTUM_DEG;
export const BEND_QUANTUM_PX = QUANTISE.BEND_QUANTUM_PX;

function clamp01(v: number): number {
  return Math.min(1, Math.max(0, v));
}

function gauss(x: number, center: number, width: number): number {
  const z = (x - center) / width;
  return Math.exp(-z * z);
}

function quantize(value: number, step: number): number {
  return Math.round(value / step) * step;
}

/** Centred moving average, clamped at the ends. Window is forced odd. */
function movingAverage(values: readonly number[], window: number): number[] {
  const half = Math.max(0, Math.floor(window / 2));
  return values.map((_, i) => {
    let sum = 0;
    let n = 0;
    for (let k = i - half; k <= i + half; k += 1) {
      const v = values[Math.min(values.length - 1, Math.max(0, k))];
      if (v === undefined) continue;
      sum += v;
      n += 1;
    }
    return n === 0 ? 0 : sum / n;
  });
}

// ---------------------------------------------------------------------------
// Ascent velocity model
// ---------------------------------------------------------------------------

/**
 * Grid resolution for integrating dt = dh / v(h).
 *
 * Deliberately NOT in spriteTuning: this is numerical accuracy, not feel.
 * Doubling it does not change how the rep looks, only how exactly the integral
 * is evaluated. STICK.MIN_VELOCITY, which does change how the rep looks, is a
 * tunable and lives there.
 */
const VELOCITY_GRID = 1024;

/**
 * Normalised ascent velocity at bar height h.
 * Exported so the inspection tool can plot the same curve the frames come from
 * rather than a redrawn approximation of it.
 */
export function ascentVelocity(h: number, loadRatio: number): number {
  const depth = byLoad(STICK.DEPTH, loadRatio);
  const v = 1 - depth * gauss(h, STICK.HEIGHT_FRAC, STICK.WIDTH);
  return Math.max(STICK.MIN_VELOCITY, v);
}

/**
 * Invert the time integral: bar height as a function of normalised ascent time.
 * Returns a lookup closure so a whole rep costs one integration.
 */
function ascentHeightSampler(loadRatio: number): (u: number) => number {
  const heights = new Float64Array(VELOCITY_GRID + 1);
  const times = new Float64Array(VELOCITY_GRID + 1);
  const dh = 1 / VELOCITY_GRID;

  let t = 0;
  heights[0] = 0;
  times[0] = 0;
  for (let j = 1; j <= VELOCITY_GRID; j += 1) {
    const hPrev = (j - 1) * dh;
    const hCur = j * dh;
    // Trapezoid on 1/v, which is where the time actually accumulates.
    const inv = 0.5 * (1 / ascentVelocity(hPrev, loadRatio) + 1 / ascentVelocity(hCur, loadRatio));
    t += inv * dh;
    heights[j] = hCur;
    times[j] = t;
  }

  const total = times[VELOCITY_GRID] ?? 1;
  for (let j = 0; j <= VELOCITY_GRID; j += 1) {
    times[j] = (times[j] ?? 0) / total;
  }

  return (u: number): number => {
    const target = clamp01(u);
    // times[] is strictly increasing, so a binary search is exact enough.
    let lo = 0;
    let hi = VELOCITY_GRID;
    while (hi - lo > 1) {
      const mid = (lo + hi) >> 1;
      if ((times[mid] ?? 0) <= target) lo = mid;
      else hi = mid;
    }
    const tLo = times[lo] ?? 0;
    const tHi = times[hi] ?? 1;
    const hLo = heights[lo] ?? 0;
    const hHi = heights[hi] ?? 1;
    const span = tHi - tLo;
    const f = span <= 0 ? 0 : (target - tLo) / span;
    return clamp01(hLo + (hHi - hLo) * f);
  };
}

// ---------------------------------------------------------------------------
// Per-phase depth
// ---------------------------------------------------------------------------

function descentDepth(u: number, loadRatio: number): number {
  const mix = byLoad(DESCENT.SMOOTHSTEP_MIX, loadRatio);
  const smooth = u * u * (3 - 2 * u);
  const shaped = (1 - mix) * u + mix * smooth;
  return BRACE_SETTLE_DEPTH + (1 - BRACE_SETTLE_DEPTH) * shaped;
}

// ---------------------------------------------------------------------------
// Bar path
// ---------------------------------------------------------------------------

function forwardDriftDescent(depth: number, loadRatio: number): number {
  const atHole = byLoad(BAR_PATH.FORWARD_AT_HOLE_PX, loadRatio);
  // Drift accumulates late in the eccentric, as the hips travel back.
  return atHole * Math.pow(clamp01(depth), BAR_PATH.FORWARD_DESCENT_EXPONENT);
}

function forwardDriftAscent(h: number, loadRatio: number): number {
  const atHole = byLoad(BAR_PATH.FORWARD_AT_HOLE_PX, loadRatio);
  const peak = byLoad(BAR_PATH.FORWARD_PX, loadRatio);
  const carried = atHole * (1 - h);
  const fight = peak * gauss(h, BAR_PATH.FORWARD_PEAK_FRAC, BAR_PATH.FORWARD_PEAK_WIDTH) * (1 - h);
  return carried + fight;
}

/**
 * Frontal-plane wobble during the grind: a steady lean plus a shake.
 * Both are gated by an envelope centred on the sticking point, so a rep that
 * never really stalls never really shakes.
 */
function grindWobble(
  h: number,
  tickInPhase: number,
  loadRatio: number,
): { lateral: number; tiltDeg: number } {
  const envelope = gauss(h, STICK.HEIGHT_FRAC, STICK.WIDTH * STICK.WOBBLE_ENVELOPE_WIDEN);
  const phase = (2 * Math.PI * tickInPhase) / STICK.OSCILLATION_PERIOD_TICKS;
  const shake = byLoad(STICK.OSCILLATION_PX, loadRatio) * Math.sin(phase);
  const lean = byLoad(BAR_PATH.LATERAL_PX, loadRatio);
  const tilt = byLoad(BAR_PATH.TILT_DEG, loadRatio);
  return {
    lateral: envelope * (lean * BAR_PATH.LATERAL_LEAN_SHARE + shake),
    tiltDeg: envelope * tilt * Math.cos(phase),
  };
}

// ---------------------------------------------------------------------------
// Strain
// ---------------------------------------------------------------------------

function phaseWeight(phase: RepPhase, depth: number, h: number): number {
  const w = STRAIN.PHASE_WEIGHT;
  switch (phase) {
    case 'BRACE':
      return w.BRACE;
    case 'DESCENT':
      return w.DESCENT_TOP + (w.DESCENT_BOTTOM - w.DESCENT_TOP) * clamp01(depth);
    case 'HOLE':
      return w.HOLE;
    case 'ASCENT':
      return clamp01(
        w.ASCENT_BASE -
          w.ASCENT_FALLOFF * h +
          w.ASCENT_STICK_BONUS * gauss(h, STICK.HEIGHT_FRAC, w.ASCENT_STICK_WIDTH),
      );
    case 'LOCKOUT':
      return w.LOCKOUT;
    default:
      return 0;
  }
}

/**
 * Strain at a point in the rep.
 *
 * Load times where-you-are, and nothing else. Forward bar drift used to be
 * added in here with a gain; it is not, and must not come back. On a maximal
 * grind — the only rep whose drift is worth drawing — the load term is already
 * near the top of the range and anything added to it is clamped straight back
 * off, so the drift's contribution reached the pixels of the LIGHT rep only.
 * Drift is now its own channel (`pitchLevelForDriftPx`), which is what lets it
 * be seen on the rep that has it.
 */
function strainFor(phase: RepPhase, depth: number, h: number, loadRatio: number): number {
  const base = byLoad(STRAIN.FROM_LOAD, loadRatio);
  return clamp01(base * phaseWeight(phase, depth, h));
}

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

interface RawTick {
  phase: RepPhase;
  direction: RepDirection;
  depth: number;
  forwardPx: number;
  lateralPx: number;
  tiltDeg: number;
  chalkPuff: number;
}

/** Tick counts per phase at a given load. Exported for the inspection tool. */
export function phaseTickCounts(loadRatio: number): Record<RepPhase, number> {
  return {
    BRACE: ticksByLoad(TIMING.BRACE_TICKS, loadRatio),
    DESCENT: ticksByLoad(TIMING.DESCENT_TICKS, loadRatio),
    HOLE: ticksByLoad(TIMING.HOLE_TICKS, loadRatio),
    ASCENT: ticksByLoad(TIMING.ASCENT_TICKS, loadRatio),
    LOCKOUT: ticksByLoad(TIMING.LOCKOUT_TICKS, loadRatio),
  };
}

/**
 * Build one squat rep.
 *
 * `loadRatio` is attempt weight over current best single: 0.55 is a comfortable
 * working set, 1.0 is a true limit attempt. Values outside LOAD_RANGE clamp.
 */
export function buildSquatRep(loadRatio: number): SquatRep {
  const load = clampLoadRatio(loadRatio);
  const counts = phaseTickCounts(load);
  const heightAt = ascentHeightSampler(load);

  const raw: RawTick[] = [];

  for (let k = 0; k < counts.BRACE; k += 1) {
    const u = counts.BRACE <= 1 ? 1 : k / (counts.BRACE - 1);
    raw.push({
      phase: 'BRACE',
      direction: 'DESCENT',
      depth: BRACE_SETTLE_DEPTH * u,
      forwardPx: 0,
      lateralPx: 0,
      tiltDeg: 0,
      chalkPuff: 0,
    });
  }

  for (let k = 0; k < counts.DESCENT; k += 1) {
    const depth = descentDepth(k / counts.DESCENT, load);
    raw.push({
      phase: 'DESCENT',
      direction: 'DESCENT',
      depth,
      forwardPx: forwardDriftDescent(depth, load),
      lateralPx: 0,
      tiltDeg: 0,
      chalkPuff: 0,
    });
  }

  for (let k = 0; k < counts.HOLE; k += 1) {
    raw.push({
      phase: 'HOLE',
      direction: 'DESCENT',
      depth: 1,
      forwardPx: forwardDriftDescent(1, load),
      lateralPx: 0,
      tiltDeg: 0,
      chalkPuff: 0,
    });
  }

  const chalkActive = load >= CHALK.MIN_LOAD_RATIO;
  for (let k = 0; k < counts.ASCENT; k += 1) {
    const h = heightAt(k / counts.ASCENT);
    const wobble = grindWobble(h, k, load);
    raw.push({
      phase: 'ASCENT',
      direction: 'ASCENT',
      depth: 1 - h,
      forwardPx: forwardDriftAscent(h, load),
      lateralPx: wobble.lateral,
      tiltDeg: wobble.tiltDeg,
      chalkPuff: chalkActive && k < CHALK.PUFF_TICKS ? 1 - k / CHALK.PUFF_TICKS : 0,
    });
  }

  for (let k = 0; k < counts.LOCKOUT; k += 1) {
    raw.push({
      phase: 'LOCKOUT',
      direction: 'ASCENT',
      depth: 0,
      forwardPx: 0,
      lateralPx: 0,
      tiltDeg: 0,
      chalkPuff: 0,
    });
  }

  // Bar whip needs the second difference of bar height, so it is a second pass.
  const barY = raw.map((r) => barYAtDepth(r.depth));
  const barYSmooth = movingAverage(barY, BEND.ACCEL_SMOOTH_TICKS);
  const staticBend = byLoad(BEND.STATIC_PX, load);

  const samples: SquatSample[] = raw.map((r, k) => {
    const yPrev = barYSmooth[k - 1] ?? barYSmooth[k] ?? 0;
    const yCur = barYSmooth[k] ?? 0;
    const yNext = barYSmooth[k + 1] ?? yCur;
    // Screen y grows downward, so upward acceleration is the negated second
    // difference. Decelerating into the hole and accelerating out of it both
    // come out positive, which is what loads the bar and bows the sleeves.
    const upAccel = -(yNext - 2 * yCur + yPrev);
    const whip = Math.min(
      BEND.MAX_WHIP_MULTIPLIER,
      Math.max(0, 1 + BEND.WHIP_GAIN * upAccel),
    );
    const bend = Math.min(BEND.MAX_PX, staticBend * whip);
    const h = 1 - r.depth;

    return {
      tick: k,
      phase: r.phase,
      direction: r.direction,
      depth: r.depth,
      barHeight: h,
      barYPx: yCur,
      barForwardPx: r.forwardPx,
      barLateralPx: r.lateralPx,
      barTiltDeg: r.tiltDeg,
      barBendPx: bend,
      strain: strainFor(r.phase, r.depth, h, load),
      chalkPuff: r.chalkPuff,
    };
  });

  const frames = coalesceFrames(samples);
  const totalTicks = samples.length;

  return {
    loadRatio: load,
    samples,
    frames,
    totalTicks,
    totalMs: totalTicks * TICK_MS,
    phaseTicks: counts,
  };
}

/** The drawn identity of a tick. Two ticks that agree here are one frame. */
interface DrawKey {
  phase: RepPhase;
  direction: RepDirection;
  poseDepth: number;
  strainLevel: number;
  pitchLevel: number;
  lateral: number;
  tilt: number;
  bend: number;
  motes: number;
}

function drawKeyFor(s: SquatSample): DrawKey {
  return {
    phase: s.phase,
    direction: s.direction,
    poseDepth: Math.round(clamp01(s.depth) * DEPTH_STEPS) / DEPTH_STEPS,
    strainLevel: strainLevel(s.strain),
    pitchLevel: pitchLevelForDriftPx(s.barForwardPx),
    lateral: Math.round(s.barLateralPx),
    tilt: quantize(s.barTiltDeg, TILT_QUANTUM_DEG),
    bend: quantize(s.barBendPx, BEND_QUANTUM_PX),
    motes: Math.round(s.chalkPuff * CHALK.MAX_MOTES),
  };
}

function sameDrawing(a: DrawKey, b: DrawKey): boolean {
  return (
    a.phase === b.phase &&
    a.direction === b.direction &&
    a.poseDepth === b.poseDepth &&
    a.strainLevel === b.strainLevel &&
    a.pitchLevel === b.pitchLevel &&
    a.lateral === b.lateral &&
    a.tilt === b.tilt &&
    a.bend === b.bend &&
    a.motes === b.motes
  );
}

/**
 * Collapse per-tick state into held frames.
 *
 * This is the animator's timing sheet, and it falls out of the model rather
 * than being authored: at a light load the drawings change nearly every tick,
 * and at the sticking point of a maximal attempt one drawing holds for a long
 * run of ticks because nothing about it has changed enough to redraw. Long
 * holds in the middle of the ascent ARE the grind.
 */
function coalesceFrames(samples: readonly SquatSample[]): SquatFrame[] {
  const frames: SquatFrame[] = [];
  let runStart = 0;

  while (runStart < samples.length) {
    const first = samples[runStart];
    if (first === undefined) break;
    const key = drawKeyFor(first);

    let end = runStart + 1;
    while (end < samples.length) {
      const next = samples[end];
      if (next === undefined) break;
      if (!sameDrawing(key, drawKeyFor(next))) break;
      end += 1;
    }

    frames.push({
      index: frames.length,
      startTick: runStart,
      holdTicks: end - runStart,
      phase: key.phase,
      direction: key.direction,
      poseDepth: key.poseDepth,
      strainLevel: key.strainLevel,
      pitchLevel: key.pitchLevel,
      barLateralPx: key.lateral,
      barTiltDeg: key.tilt,
      barBendPx: key.bend,
      chalkMotes: key.motes,
      sample: first,
    });

    runStart = end;
  }

  return frames;
}

// ---------------------------------------------------------------------------
// Analysis. Plain, boring functions — the tests and the inspection tool both
// use these, so they must not be clever enough to hide a problem.
// ---------------------------------------------------------------------------

export function ascentSamples(rep: SquatRep): readonly SquatSample[] {
  return rep.samples.filter((s) => s.phase === 'ASCENT');
}

/** Per-tick rise in normalised bar height during the ascent. */
export function ascentRisePerTick(rep: SquatRep): number[] {
  const asc = ascentSamples(rep);
  const out: number[] = [];
  for (let i = 1; i < asc.length; i += 1) {
    const a = asc[i - 1];
    const b = asc[i];
    if (a === undefined || b === undefined) continue;
    out.push(b.barHeight - a.barHeight);
  }
  return out;
}

export interface StallRun {
  readonly ticks: number;
  /** Normalised bar height where the longest stall begins. */
  readonly atHeight: number;
}

/**
 * Longest run of consecutive ascent ticks whose rise is below
 * STICK.STALL_EPSILON. This is the grind, measured rather than asserted.
 */
export function longestStall(rep: SquatRep): StallRun {
  const asc = ascentSamples(rep);
  const rises = ascentRisePerTick(rep);
  let best = 0;
  let bestStart = 0;
  let run = 0;
  let runStart = 0;

  for (let i = 0; i < rises.length; i += 1) {
    const rise = rises[i] ?? Number.POSITIVE_INFINITY;
    if (rise < STICK.STALL_EPSILON) {
      if (run === 0) runStart = i;
      run += 1;
      if (run > best) {
        best = run;
        bestStart = runStart;
      }
    } else {
      run = 0;
    }
  }

  return { ticks: best, atHeight: asc[bestStart]?.barHeight ?? 0 };
}

/**
 * Ascent bar height resampled to `steps` equally spaced points in NORMALISED
 * time. Duration is divided out, so anything this measures is shape.
 */
export function normalisedAscentProfile(rep: SquatRep, steps: number): number[] {
  const asc = ascentSamples(rep);
  if (asc.length === 0) return [];
  const out: number[] = [];
  for (let i = 0; i < steps; i += 1) {
    const u = steps <= 1 ? 0 : i / (steps - 1);
    const pos = u * (asc.length - 1);
    const lo = Math.floor(pos);
    const hi = Math.min(asc.length - 1, lo + 1);
    const f = pos - lo;
    const a = asc[lo]?.barHeight ?? 0;
    const b = asc[hi]?.barHeight ?? a;
    out.push(a + (b - a) * f);
  }
  return out;
}

/**
 * Coefficient of variation of the resampled ascent's step sizes.
 *
 * Zero means the bar rose at a perfectly constant rate. Large means the rep had
 * fast parts and near-stopped parts. Because the profile is in normalised time,
 * a rep that is simply a slowed-down copy of another scores IDENTICALLY. This
 * is the number that separates "heavier" from "slower".
 */
export function ascentShapeVariation(rep: SquatRep, steps: number = 64): number {
  const profile = normalisedAscentProfile(rep, steps);
  const deltas: number[] = [];
  for (let i = 1; i < profile.length; i += 1) {
    deltas.push((profile[i] ?? 0) - (profile[i - 1] ?? 0));
  }
  if (deltas.length === 0) return 0;
  const mean = deltas.reduce((a, b) => a + b, 0) / deltas.length;
  if (mean === 0) return 0;
  const variance = deltas.reduce((a, d) => a + (d - mean) * (d - mean), 0) / deltas.length;
  return Math.sqrt(variance) / Math.abs(mean);
}

/** Peak sagittal deviation of the bar from the vertical, px. */
export function peakForwardDeviationPx(rep: SquatRep): number {
  return rep.samples.reduce((m, s) => Math.max(m, Math.abs(s.barForwardPx)), 0);
}

/** Peak frontal-plane deviation of the bar centre, px. */
export function peakLateralDeviationPx(rep: SquatRep): number {
  return rep.samples.reduce((m, s) => Math.max(m, Math.abs(s.barLateralPx)), 0);
}

export function peakBendPx(rep: SquatRep): number {
  return rep.samples.reduce((m, s) => Math.max(m, s.barBendPx), 0);
}

/** Share of the rep's ticks spent in the concentric. */
export function ascentTickFraction(rep: SquatRep): number {
  return rep.totalTicks === 0 ? 0 : rep.phaseTicks.ASCENT / rep.totalTicks;
}

/** Longest single held frame, in ticks. */
export function longestHoldTicks(rep: SquatRep): number {
  return rep.frames.reduce((m, f) => Math.max(m, f.holdTicks), 0);
}

/**
 * Longest held frame within the concentric.
 *
 * The plain `longestHoldTicks` is usually won by the setup brace, where the
 * lifter is standing still on purpose and nothing is being ground out.
 *
 * NOTE, because it is easy to over-read: this does NOT go up much with load,
 * and that is correct rather than a failure. During a grind the drawing keeps
 * changing every couple of ticks — the bar shakes and tilts even though it is
 * not rising — so the ticks pile up in a short cycle of frames rather than in
 * one long hold. `longestAscentPoseRunTicks` is the metric that captures "the
 * bar stopped moving"; this one captures "the drawing stopped changing", and a
 * grinding sprite should fail the second while passing the first.
 */
export function longestAscentHoldTicks(rep: SquatRep): number {
  return rep.frames
    .filter((f) => f.phase === 'ASCENT')
    .reduce((m, f) => Math.max(m, f.holdTicks), 0);
}

/**
 * Longest run of consecutive concentric ticks that resolve to the same authored
 * depth step — i.e. how long the bar sits at one height while the lifter fights
 * it. This is the drawing-level statement of the sticking point.
 */
export function longestAscentPoseRunTicks(rep: SquatRep): number {
  const asc = ascentSamples(rep);
  let best = 0;
  let run = 0;
  let prev: number | null = null;
  for (const s of asc) {
    const step = Math.round(clamp01(s.depth) * DEPTH_STEPS);
    if (prev !== null && step === prev) run += 1;
    else run = 1;
    prev = step;
    if (run > best) best = run;
  }
  return best;
}

/**
 * Distinct BODY drawings a rep needs — i.e. how much sheet the lifter costs.
 *
 * Deliberately keyed on the body's own state only. Bar bend, tilt and lateral
 * shake are drawn on the bar, not on him, and counting them here would let a
 * shaking barbell inflate the figure "the lifter is more animated under load".
 */
export function distinctDrawingCount(rep: SquatRep): number {
  const seen = new Set<string>();
  for (const f of rep.frames) {
    seen.add(`${f.direction}:${f.poseDepth}:${f.strainLevel}:${f.pitchLevel}`);
  }
  return seen.size;
}

/** Highest strain level the rep ever draws. */
export function peakStrainLevel(rep: SquatRep): number {
  return rep.frames.reduce((m, f) => Math.max(m, f.strainLevel), 0);
}

/** Highest pitch level the rep ever draws. */
export function peakPitchLevel(rep: SquatRep): number {
  return rep.frames.reduce((m, f) => Math.max(m, f.pitchLevel), 0);
}

/**
 * The frame a rep is drawing at its sticking point — the ugliest frame it has.
 *
 * Defined as the concentric frame whose sample is nearest STICK.HEIGHT_FRAC,
 * so it is the same point of the lift for every load rather than the same tick.
 * This is the frame the light-vs-maximal body comparison is made at.
 */
export function stickingPointFrame(rep: SquatRep): SquatFrame | undefined {
  let best: SquatFrame | undefined;
  let bestErr = Infinity;
  for (const f of rep.frames) {
    if (f.phase !== 'ASCENT') continue;
    const err = Math.abs(f.sample.barHeight - STICK.HEIGHT_FRAC);
    if (err < bestErr) {
      bestErr = err;
      best = f;
    }
  }
  return best;
}

/** Convenience: the two reps the contact sheet compares. */
export function buildComparisonPair(): { light: SquatRep; maximal: SquatRep } {
  return {
    light: buildSquatRep(LOAD_PRESETS.LIGHT),
    maximal: buildSquatRep(LOAD_PRESETS.MAXIMAL),
  };
}
