/** Native facility layout, interaction, and accessibility values for phone playtesting. */
export const NATIVE_FACILITY_TUNING = Object.freeze({
  SCENE_FALLBACK_WIDTH: 390,
  SCENE_FALLBACK_HEIGHT: 430,
  FACILITY_REFRESH_MS: 1000,
  CLOCK_FOREGROUND_GAP_MS: 15000,
  SIM_FRAME_MS: 16,
  SIM_CATCHUP_MAX_TICKS: 8,
  DRAG_THRESHOLD_PX: 5,
  PREVIEW_PULSE_MS: 170,
  HAPTIC_MIN_GAP_MS: 80,
  SOUND_VOLUME: 0.25,
  ZOOM_STEP: 0.18,
  QUARTER_TURN: 90,
  FULL_TURN: 360,
  RADIANS_TO_DEGREES: 180 / Math.PI,
  DRAWER_MAX_HEIGHT: 190,
  DRAWER_BOTTOM_SPACE: 88,
  PAD: 16,
  GAP: 8,
  SMALL_GAP: 4,
  TITLE_FONT: 25,
  TITLE_TRACKING: 0.2,
  BODY_FONT: 13,
  SMALL_FONT: 11,
  LABEL_FONT: 10,
  BUTTON_FONT: 12,
  BUTTON_HEIGHT: 42,
  BUTTON_RADIUS: 8,
  BORDER: 1,
  INVENTORY_HEIGHT: 38,
  CHIP_PAD: 8,
  MUTED_OPACITY: 0.4,
  LETTER_SPACING: 1.4,
  FONT_BOLD: '800' as const,
  FONT_MEDIUM: '600' as const,
});

export const NATIVE_FACILITY_PALETTE = Object.freeze({
  ESPRESSO: '#1c1511',
  PANEL: '#241d18',
  PANEL_EDGE: '#514136',
  IVORY: '#f5ead7',
  MUTED: '#b7a592',
  AMBER: '#efad4d',
  AMBER_INK: '#251908',
  ERROR: '#f2a397',
  VALID: '#91c999',
});

export const NATIVE_FACILITY_COPY = Object.freeze({
  rung: Object.freeze({
    garage: 'Garage gym',
    'storage-unit': 'The storage gym',
    'strip-mall-unit': 'Neighborhood gym',
    warehouse: 'Warehouse gym',
  }),
  items: Object.freeze({
    'power-bar': 'Power bar', 'comp-plates': 'Competition plates',
    'flat-bench': 'Competition bench', 'squat-rack': 'Squat rack',
    bike: 'Exercise bike', treadmill: 'Treadmill', rower: 'Rower', sled: 'Sled track',
    dumbbells: 'Dumbbell set', cables: 'Cable station', machines: 'Machine station',
    mats: 'Training mats', 'foam-rollers': 'Foam rollers', sauna: 'Sauna',
    'wrist-wraps': 'Wrist wraps', belts: 'Lifting belts', sleeves: 'Knee sleeves',
    'specialty-bars': 'Specialty bars',
  }),
  managers: Object.freeze({ novice: 'Floor assistant', steady: 'Gym manager', veteran: 'Head coach' }),
  tabs: Object.freeze(['gym', 'build', 'shop', 'staff'] as const),
});
