/**
 * calendar.ts — GDD §6.1's Career calendar: local -> regional -> nationals ->
 * worlds, as dated events a lifter can be shown.
 *
 * Pure: no clock, no I/O, no React. The caller says which day it is, exactly as
 * `streak.ts` requires of its own callers and for the same reason — resolving
 * "when is now" needs a timezone, and a timezone is a fact about an account
 * rather than about a calendar.
 *
 * ---------------------------------------------------------------------------
 * 1. WHAT "WHEN" IS ANCHORED TO
 * ---------------------------------------------------------------------------
 * Every day in this module is a `StreakDay` from `src/game/streak.ts`: an
 * integer count of local civil days since 1970-01-01, produced from a wall
 * clock by `streakDayFromLocalWallClock`, which applies the rollover hour.
 *
 * Reusing that type is deliberate and it is the whole of this module's answer
 * to a hazard this codebase has already paid for twice. A second day scale —
 * a `Date`, a millisecond stamp, an "index since signup" — is a second
 * definition of what today is, and the two disagree on exactly the boundary
 * nobody tests. There is one day scale in this repository and the calendar is
 * on it.
 *
 * The series themselves are measured from `CAREER_TUNING.SEASON_ANCHOR`, one
 * absolute civil date shared by every account. GDD §6.6 forces that for the top
 * two tiers: nationals and worlds are "scheduled live windows" with a flight
 * order and a live leaderboard, which is a thing every entrant is inside at the
 * same moment. A per-signup anchor cannot express that, and having two anchors
 * — one for the async tiers, one for the sync ones — would be the same
 * disagreement in a different place.
 *
 * WHAT THIS COSTS, said plainly: a lifter who signs up in year three has meets
 * behind them they never entered, and the calendar simply does not show them
 * (nothing before `today` is generated by `upcomingMeets`). A signup-anchored
 * calendar would have given them a personal season starting the day they
 * arrived. That is a real difference in feel and a human may want the other
 * one for the async half.
 *
 * ---------------------------------------------------------------------------
 * 2. THE BOUNDARIES, WHICH ARE THE PART THAT BITES
 * ---------------------------------------------------------------------------
 *   - A window `[fromDay, toDay]` is INCLUSIVE at both ends. A meet on the
 *     first day of the window is in it, and so is one on the last.
 *   - `fromDay > toDay` yields nothing, rather than throwing: an empty window
 *     is a legitimate question with an empty answer.
 *   - A tier's series starts at the anchor plus its phase and runs forward.
 *     Nothing is generated before that day, so a window entirely before the
 *     anchor is empty rather than negative.
 *   - A meet is generated on the day it is held. Whether that day is still
 *     enterable is `eligibility.ts`'s question, and the two are kept apart on
 *     purpose: a calendar that hides a meet the moment it starts cannot draw
 *     "today" and a schedule that never expires cannot refuse one.
 */

import {
  addDays,
  asStreakDay,
  civilDateFromStreakDay,
  streakDayFromCivilDate,
  type StreakDay,
} from '../game/streak';
import {
  CAREER_COPY,
  CAREER_TUNING,
  MEET_TIER_ORDER,
  TIER_SCHEDULING,
  type CareerFederationId,
  type CareerMeetTier,
  type CareerRuleset,
  type MeetSchedulingMode,
} from './careerTuning';
import { federationById, tierIndex, CAREER_FEDERATION_IDS } from './federation';

/**
 * One dated event on the calendar.
 *
 * Every field is derived from the federation, the tier and the day. There is no
 * hand-written meet row anywhere in this module, so a calendar cannot disagree
 * with itself about when a meet is or what it asks for.
 *
 * It is deliberately NOT `MeetDefinition` from `src/game/meetTuning.ts`. That
 * type carries the things a meet needs to be RUN — loading rules, a ghost field
 * to be placed against, a venue — and this module schedules meets rather than
 * running them. The adapter between the two is the wiring piece, and it is the
 * one place that has to decide where a scheduled meet is held.
 */
export interface CareerMeet {
  /** Stable and derived: federation, tier and date. */
  readonly id: string;
  readonly federationId: CareerFederationId;
  /** Fictional (GDD §12.3). Copied from the federation so a screen can draw it. */
  readonly federationName: string;
  readonly ruleset: CareerRuleset;
  readonly tier: CareerMeetTier;
  readonly scheduling: MeetSchedulingMode;
  /** What a screen calls it: the federation's name and the tier's. */
  readonly name: string;
  readonly day: StreakDay;
  /** The same day as `YYYY-MM-DD`, the format `resultCard.ts` parses. */
  readonly dateIso: string;
  /** `null` on an open tier. Kilograms. */
  readonly qualifyingTotalKg: number | null;
}

/** The season anchor as a day index. */
export function seasonAnchorDay(): StreakDay {
  return streakDayFromCivilDate(CAREER_TUNING.SEASON_ANCHOR);
}

/** The first day of a tier's series: the anchor plus that tier's phase. */
export function tierSeriesStartDay(tier: CareerMeetTier): StreakDay {
  return addDays(seasonAnchorDay(), CAREER_TUNING.PHASE_DAYS[tier]);
}

/** What a tier asks for, in kilograms. `null` means open entry. */
export function qualifyingTotalKgFor(tier: CareerMeetTier): number | null {
  return CAREER_TUNING.QUALIFYING_TOTAL_KG[tier];
}

/** `YYYY-MM-DD` for a day index. */
export function isoDateOf(day: StreakDay): string {
  const { year, month, day: dayOfMonth } = civilDateFromStreakDay(day);
  const paddedMonth = String(month).padStart(2, '0');
  const paddedDay = String(dayOfMonth).padStart(2, '0');
  return `${year}-${paddedMonth}-${paddedDay}`;
}

/**
 * Is this day one of the tier's meet days?
 *
 * The predicate `meetDaysForTier` is built from, exposed because the wiring
 * needs to ask about one day without generating a window.
 */
export function isMeetDayForTier(tier: CareerMeetTier, day: StreakDay): boolean {
  const start = tierSeriesStartDay(tier);
  const offset = day - start;
  if (offset < 0) return false;
  return offset % CAREER_TUNING.CADENCE_DAYS[tier] === 0;
}

/**
 * Every day in `[fromDay, toDay]` this tier holds a meet on, in order.
 *
 * Empty when the window is empty, when it ends before the series starts, or
 * when it is inverted.
 */
export function meetDaysForTier(
  tier: CareerMeetTier,
  fromDay: StreakDay,
  toDay: StreakDay,
): readonly StreakDay[] {
  if (toDay < fromDay) return [];
  const start = tierSeriesStartDay(tier);
  if (toDay < start) return [];
  const cadence = CAREER_TUNING.CADENCE_DAYS[tier];
  const firstIndex = fromDay <= start ? 0 : Math.ceil((fromDay - start) / cadence);
  const days: StreakDay[] = [];
  for (let index = firstIndex; ; index += 1) {
    const day = addDays(start, index * cadence);
    if (day > toDay) break;
    days.push(day);
  }
  return days;
}

/** The meet this federation holds at this tier on this day. */
export function careerMeetFor(
  federationId: CareerFederationId,
  tier: CareerMeetTier,
  day: StreakDay,
): CareerMeet {
  const federation = federationById(federationId);
  const dateIso = isoDateOf(day);
  return {
    id: `${federationId}-${tier}-${dateIso}`,
    federationId,
    federationName: federation.name,
    ruleset: federation.ruleset,
    tier,
    scheduling: TIER_SCHEDULING[tier],
    name: `${federation.name} ${CAREER_COPY.TIER_MEET_NAME[tier]}`,
    day,
    dateIso,
    qualifyingTotalKg: qualifyingTotalKgFor(tier),
  };
}

/**
 * Reconstruct the scheduled meet a stored id names, or `null` if the string
 * is not one this calendar can have produced.
 *
 * Parse from the RIGHT, because both the federation and the tier may contain
 * hyphens (`anvil-coast`, `campaign-worlds`). The tail is a civil date
 * `YYYY-MM-DD`; the longest matching tier wins; the rest is the federation.
 * A well-formed id for a day that is not that tier's meet day is still
 * `null` — the calendar does not invent meets it would not have scheduled.
 */
const TIERS_LONGEST_FIRST: readonly CareerMeetTier[] = [...MEET_TIER_ORDER].sort(
  (a, b) => b.length - a.length,
);

const CAREER_MEET_ID_TAIL = /^(.+)-(\d{4}-\d{2}-\d{2})$/;
const CAREER_MEET_DATE_ISO = /^(\d{4})-(\d{2})-(\d{2})$/;

function isCareerFederationId(value: string): value is CareerFederationId {
  return (CAREER_FEDERATION_IDS as readonly string[]).includes(value);
}

export function careerMeetFromId(id: string): CareerMeet | null {
  if (typeof id !== 'string' || id.length === 0) return null;
  const tail = CAREER_MEET_ID_TAIL.exec(id);
  if (tail === null) return null;
  const rest = tail[1];
  const dateIso = tail[2];
  if (rest === undefined || dateIso === undefined) return null;
  const dateParts = CAREER_MEET_DATE_ISO.exec(dateIso);
  if (dateParts === null) return null;
  const [, yearText, monthText, dayText] = dateParts;
  if (yearText === undefined || monthText === undefined || dayText === undefined) return null;
  const year = Number(yearText);
  const month = Number(monthText);
  const dayOfMonth = Number(dayText);
  let day: StreakDay;
  try {
    day = streakDayFromCivilDate({ year, month, day: dayOfMonth });
  } catch {
    return null;
  }
  if (isoDateOf(day) !== dateIso) return null;
  let tier: CareerMeetTier | null = null;
  let federationPart: string | null = null;
  for (const candidate of TIERS_LONGEST_FIRST) {
    const suffix = `-${candidate}`;
    if (rest.endsWith(suffix)) {
      tier = candidate;
      federationPart = rest.slice(0, rest.length - suffix.length);
      break;
    }
  }
  if (tier === null || federationPart === null || !isCareerFederationId(federationPart)) {
    return null;
  }
  if (!isMeetDayForTier(tier, day)) return null;
  return careerMeetFor(federationPart, tier, day);
}

/**
 * Every meet this federation holds in `[fromDay, toDay]`, soonest first.
 *
 * Ties break on the tier ladder, lowest tier first. At the shipped tuning no
 * two tiers share a day (see `PHASE_DAYS`), so the tie-break is unreachable
 * there and exists so that a tuner who makes them collide gets a stable order
 * rather than whichever order the tier loop happened to run in.
 */
export function scheduledMeets(
  federationId: CareerFederationId,
  fromDay: StreakDay,
  toDay: StreakDay,
): readonly CareerMeet[] {
  const meets: CareerMeet[] = [];
  for (const tier of MEET_TIER_ORDER) {
    for (const day of meetDaysForTier(tier, fromDay, toDay)) {
      meets.push(careerMeetFor(federationId, tier, day));
    }
  }
  return meets.sort((a, b) => (a.day === b.day ? tierIndex(a.tier) - tierIndex(b.tier) : a.day - b.day));
}

/**
 * The meets from `today` to the end of the horizon, soonest first.
 *
 * `today` is included: a meet held today is on the calendar, and whether it can
 * still be entered is `eligibility.ts`'s call rather than the schedule's.
 */
export function upcomingMeets(
  federationId: CareerFederationId,
  today: StreakDay,
  horizonDays: number = CAREER_TUNING.HORIZON_DAYS,
): readonly CareerMeet[] {
  if (!Number.isSafeInteger(horizonDays) || horizonDays < 0) {
    throw new RangeError(`career: a horizon must be a whole number of days, received ${horizonDays}`);
  }
  return scheduledMeets(federationId, today, addDays(today, horizonDays));
}

/**
 * The next meet of one tier on or after `fromDay`, or `null` if the horizon
 * given holds none.
 */
export function nextMeetOfTier(
  federationId: CareerFederationId,
  tier: CareerMeetTier,
  fromDay: StreakDay,
  horizonDays: number = CAREER_TUNING.HORIZON_DAYS,
): CareerMeet | null {
  const days = meetDaysForTier(tier, fromDay, addDays(fromDay, horizonDays));
  const first = days[0];
  return first === undefined ? null : careerMeetFor(federationId, tier, first);
}

/**
 * How many days of `[fromDay, toDay]` hold more than one meet for this
 * federation.
 *
 * A census rather than a rule. The shipped phases put the five tiers on five
 * different weekdays so this reports nothing; a tuner who moves a phase onto
 * another tier's weekday makes it report, which is the point. Two meets on one
 * day is not a defect in this module — a lifter cannot be at both, and which
 * one wins is scheduling design GDD §6.1 does not specify.
 */
export function collidingMeetDays(
  federationId: CareerFederationId,
  fromDay: StreakDay,
  toDay: StreakDay,
): readonly StreakDay[] {
  const seen = new Map<number, number>();
  for (const meet of scheduledMeets(federationId, fromDay, toDay)) {
    seen.set(meet.day, (seen.get(meet.day) ?? 0) + 1);
  }
  return [...seen.entries()]
    .filter(([, count]) => count > 1)
    .map(([day]) => asStreakDay(day))
    .sort((a, b) => a - b);
}
