#!/usr/bin/env node
// tools/athleteTraces.mjs — write or check the canonical squat trace corpus.
//
//   node tools/athleteTraces.mjs check            the committed corpus equals what the mechanic produces today (exit 1 on drift)
//   node tools/athleteTraces.mjs write            regenerate docs/design/athlete-traces/ from src/art/athleteTraces.ts
//   node tools/athleteTraces.mjs replay <file>    replay one record's own config + script and report whether its ticks reproduce
//   ... [--dir <directory>]                       read/write somewhere other than the committed corpus
//
// THE CORPUS IS GENERATED, NEVER EDITED. Every file under
// `docs/design/athlete-traces/` is `src/art/athleteTraces.ts`'s output — the
// real mechanic (`runLift`) on a scripted rep, read through
// `liftPresentation(state, totalKg, prior)` and `athleteRigInputsFrom` every
// tick. `check` is what `src/art/athleteTraces.test.ts` and the post-delivery
// gate run; `write` is what a mechanics retune that legitimately moves a
// trace is followed by, in the same commit. `replay` is the acceptance
// harness's question — "does this file's own recipe still produce this
// file's own ticks?" — asked of one record without the scenario table.
//
// Loads the TypeScript through the same `transpileModule` hook
// `tools/rivContract.mjs` uses (no bundler is installed here). Declares no
// dev-server URL and drives nothing.
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

export const README_NAME = 'README.md';

/** Load any repo `.ts` module through a scoped `.ts` loader (CommonJS transpile, no bundler). */
export function loadTsModule(relPath) {
  const ts = require('typescript');
  const Module = require('node:module');
  const extensions = Module._extensions;
  const previous = extensions['.ts'];
  extensions['.ts'] = (module, filename) => {
    const source = readFileSync(filename, 'utf8');
    const { outputText } = ts.transpileModule(source, {
      fileName: filename,
      compilerOptions: {
        module: ts.ModuleKind.CommonJS,
        target: ts.ScriptTarget.ES2022,
        esModuleInterop: true,
      },
    });
    module._compile(outputText, filename);
  };
  try {
    return require(path.join(REPO_ROOT, relPath));
  } finally {
    if (previous === undefined) delete extensions['.ts'];
    else extensions['.ts'] = previous;
  }
}

/** Load `src/art/athleteTraces.ts`. */
export function loadTraces() {
  return loadTsModule('src/art/athleteTraces.ts');
}

/** The README the corpus carries: what each file is and how to reproduce it. Generated, so `check` pins it too. */
export function readmeFor(traces, mod) {
  const rows = traces.map((t) => {
    const script = t.script.map((s) => `${s.kind}@${s.tick}`).join(', ');
    const outcome = t.summary.missReason === null ? t.summary.outcome : `${t.summary.outcome}/${t.summary.missReason}`;
    return `| \`${mod.athleteTraceFileName(t.scenario)}\` | ${t.scenario.title} | ${t.config.loadRatio} | ${t.totalKg} kg | ${t.config.seed} | ${script} | ${outcome} | ${t.summary.ticks} |`;
  });
  return [
    '# Athlete traces — the canonical squat input corpus',
    '',
    'GENERATED by `node tools/athleteTraces.mjs write` from `src/art/athleteTraces.ts`. Do not edit;',
    '`node tools/athleteTraces.mjs check` (run by `src/art/athleteTraces.test.ts`) fails on any byte that',
    'differs from what the mechanic produces on the current tree.',
    '',
    'Each file is one scripted squat rep driven through the REAL mechanic — `runLift(config, script)` in',
    '`src/game/lift.ts` — and recorded every tick through the frozen presentation contract',
    '`liftPresentation(state, totalKg, prior)` (`prior` = the previous tick) and the rig binding',
    '`athleteRigInputsFrom(...)`. Per tick the file carries `presentation` (the full `LiftPresentationState`:',
    'phase, barHeight, barVelocity, motionSampleValid, integratorVelocity, strain, grindIntensity, effortBand,',
    'depthAchieved, lockedOut, complete, outcome, missReason, load and discs, command state, events, resolution)',
    'and `rig` (the full `AthleteRigInputs` record the production stage writes, plate slots included).',
    '`rigInputValues(rig)` is the ordered write list; it is derived, not stored.',
    '',
    'Nothing in a trace is hand-authored. The only synthetic inputs are the script (which tick the finger',
    'went down or up) and the seed, both recorded in the file, so `config` + `script` reproduce the ticks:',
    '`node tools/athleteTraces.mjs replay docs/design/athlete-traces/<file>`.',
    '',
    `Seed ${traces[0]?.config.seed ?? ''} is the seed \`LiftScreen\` gives a player's first rep; total kg is the demo best single`,
    `(${traces[0]?.bestSingleKg ?? ''} kg) times the load ratio, rounded the way the screen rounds it.`,
    '',
    '| File | Scenario | Load ratio | Bar | Seed | Script (input@tick) | Outcome | Ticks |',
    '|---|---|---|---|---|---|---|---|',
    ...rows,
    '',
    'Script recipes, in the mechanic\'s terms:',
    '',
    ...traces.map((t) => `- **${t.scenario.title}** (\`${t.scenario.id}\`): ${t.scenario.how}`),
    '',
  ].join('\n');
}

/** Every file the corpus should hold, name → content. */
export function expectedFiles(mod) {
  const traces = mod.athleteTraces();
  const files = new Map();
  for (const trace of traces) files.set(mod.athleteTraceFileName(trace.scenario), mod.serializeAthleteTrace(trace));
  files.set(README_NAME, readmeFor(traces, mod));
  return files;
}

export function writeCorpus(dir, mod) {
  mkdirSync(dir, { recursive: true });
  const files = expectedFiles(mod);
  for (const [name, content] of files) writeFileSync(path.join(dir, name), content);
  return [...files.keys()];
}

/** `{ ok, lines }`: every expected file present and byte-identical, and nothing else in the directory. */
export function checkCorpus(dir, mod) {
  const files = expectedFiles(mod);
  const lines = [];
  let ok = true;
  const present = existsSync(dir) ? readdirSync(dir).sort() : [];
  for (const [name, content] of files) {
    const file = path.join(dir, name);
    if (!existsSync(file)) {
      ok = false;
      lines.push(`MISSING  ${name}`);
      continue;
    }
    const actual = readFileSync(file, 'utf8');
    if (actual === content) {
      lines.push(`ok       ${name}`);
    } else {
      ok = false;
      lines.push(`DRIFT    ${name} (${actual.length} bytes on disk, ${content.length} expected)`);
    }
  }
  for (const name of present) {
    if (!files.has(name)) {
      ok = false;
      lines.push(`STRAY    ${name} — not generated by src/art/athleteTraces.ts`);
    }
  }
  lines.push(ok ? 'ATHLETE_TRACES_CURRENT' : 'ATHLETE_TRACES_DRIFT — run: node tools/athleteTraces.mjs write');
  return { ok, lines };
}

/** Replay one record's own `config` + `script` and compare to its own `ticks`. */
export function replayRecord(file, mod) {
  const record = JSON.parse(readFileSync(file, 'utf8'));
  const ticks = mod.athleteTraceTicks(record.config, record.script, record.totalKg);
  const expected = JSON.stringify(record.ticks);
  const actual = JSON.stringify(ticks);
  const lines = [
    `${path.basename(file)}: ${record.scenario?.title ?? '?'} — load ${record.config.loadRatio}, seed ${record.config.seed}, ${record.script.length} inputs`,
    `  recorded ${record.ticks.length} ticks, replay produced ${ticks.length}`,
  ];
  if (expected === actual) {
    lines.push(`  ATHLETE_TRACE_REPRODUCES — outcome ${record.summary?.outcome}/${record.summary?.missReason}`);
    return { ok: true, lines, record, ticks };
  }
  let first = -1;
  for (let i = 0; i < Math.max(ticks.length, record.ticks.length); i += 1) {
    if (JSON.stringify(ticks[i]) !== JSON.stringify(record.ticks[i])) {
      first = i;
      break;
    }
  }
  lines.push(`  ATHLETE_TRACE_DIVERGED — first differing tick index ${first}`);
  return { ok: false, lines, record, ticks };
}

function main(argv) {
  let dir = path.join(REPO_ROOT, loadTracesDir());
  const positional = [];
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === '--dir') {
      dir = path.resolve(REPO_ROOT, argv[i + 1] ?? '');
      i += 1;
    } else {
      positional.push(argv[i]);
    }
  }
  const [command, target] = positional;
  const mod = loadTraces();
  if (command === 'write') {
    const names = writeCorpus(dir, mod);
    process.stdout.write(`wrote ${names.length} files to ${path.relative(REPO_ROOT, dir)}: ${names.join(', ')}\n`);
    return 0;
  }
  if (command === 'check') {
    const { ok, lines } = checkCorpus(dir, mod);
    process.stdout.write(`${lines.join('\n')}\n`);
    return ok ? 0 : 1;
  }
  if (command === 'replay' && target !== undefined) {
    const { ok, lines } = replayRecord(path.resolve(REPO_ROOT, target), mod);
    process.stdout.write(`${lines.join('\n')}\n`);
    return ok ? 0 : 1;
  }
  process.stderr.write('usage: node tools/athleteTraces.mjs check|write [--dir <directory>] | replay <file.json>\n');
  return 2;
}

function loadTracesDir() {
  // The directory is the module's own constant; read it without the loader
  // so `--help` paths do not compile the whole engine.
  const source = readFileSync(path.join(REPO_ROOT, 'src/art/athleteTraces.ts'), 'utf8');
  const m = source.match(/ATHLETE_TRACE_DIR = '([^']+)'/);
  return m ? m[1] : 'docs/design/athlete-traces';
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exit(main(process.argv.slice(2)));
}
