import { LIFT_TUNING } from '../../src/game/liftTuning';

/** Browser presentation only; the native lift engine owns every game beat. */
export const BROWSER_LIFT_TUNING = Object.freeze({
  HITCH_PAUSE_MS: 250,
  MAX_CATCH_UP_TICKS: LIFT_TUNING.FEEDBACK.MAX_CATCH_UP_TICKS,
  CUE_VIEW_SIZE: 120,
  CUE_VIEW_CENTER: 60,
  CUE_STROKE: LIFT_TUNING.FEEDBACK.CUE_RING_STROKE,
  SQUAT_DESCENT_FIRST: 0.35,
  SQUAT_DESCENT_SECOND: 0.9,
  SQUAT_ASCENT_FIRST: 0.35,
  SQUAT_ASCENT_SECOND: 0.62,
  SQUAT_ASCENT_THIRD: 0.88,
  BENCH_DESCENT_FIRST: 0.35,
  BENCH_DESCENT_SECOND: 0.75,
  BENCH_ASCENT_FIRST: 0.4,
  BENCH_ASCENT_SECOND: 0.75,
  DEADLIFT_HEIGHT_FIRST: 0.22,
  DEADLIFT_HEIGHT_SECOND: 0.42,
  DEADLIFT_HEIGHT_THIRD: 0.62,
  DEADLIFT_HEIGHT_FOURTH: 0.82,
});

export const ATHLETE_ATLAS = Object.freeze({
  columns: 3,
  rows: 2,
  canvasSize: 512,
  groundLine: 460,
  visibleAlpha: 16,
  pixelChannels: 4,
  alphaChannel: 3,
  poses: Object.freeze({ brace: 1, halfDescent: 2, bottom: 3, lowDrive: 4, highDrive: 5, lockout: 6 }),
});

export const RESULT_SHEET_LAYOUT = Object.freeze({
  width: 1600,
  height: 1060,
  margin: 58,
  titleY: 94,
  meetY: 151,
  categoryY: 193,
  tableY: 252,
  headingY: 286,
  headerHeight: 54,
  rowHeight: 62,
  footerY: 988,
  fineRule: 1,
  heavyRule: 2,
  fallbackWidth: 70,
  cellPadding: 8,
  rowPadding: 12,
  columnWeights: Object.freeze([52, 46, 230, 84, 71, 71, 71, 76, 71, 71, 71, 76, 71, 71, 71, 76, 94, 106]),
  titleFont: '700 42px Arial',
  meetFont: '700 27px Arial',
  categoryFont: '17px Arial',
  groupFont: '700 17px Arial',
  columnFont: '700 15px Arial',
  nameFont: '700 19px Arial',
  cellFont: '19px Arial',
  footerFont: '16px Arial',
  groupHeight: 40,
  groupHeadingOffset: 26,
  columnHeadingOffset: 35,
  rowTextOffset: 39,
  downloadUrlLifetimeMs: 1000,
});
