/** Presentation and interaction values; the facility owns progression. */
export const GYM_INTERACTION_TUNING = Object.freeze({
  ZERO: 0, ONE: 1, TWO: 2, PERCENT: 100, QUARTER_TURN: 90, FULL_TURN: 360,
  SECOND_MS: 1000, STEP_MS: 100, MAX_FRAME_GAP_MS: 160, MAX_DPR: 2,
  INITIAL_WIDTH: 390, INITIAL_HEIGHT: 420, REPORT_INTERVAL_MS: 400,
  MAX_PERFORMANCE_SAMPLES: 600, DEFAULT_ZOOM: 1.4, ZOOM_STEP: .2, MIN_ZOOM: .3, MAX_ZOOM: 2.8,
  TAP_SLOP_PX: 7, PREVIEW_WIDTH: 120, PREVIEW_HEIGHT: 100,
  FEEDBACK_DURATION_SECONDS: .075, FEEDBACK_VOLUME: .025,
  FEEDBACK_FREQUENCY: 360, FEEDBACK_END_FREQUENCY: 180,
});
