/** Presentation geometry and texture decoding. Gameplay remains in native tuning. */
export const INTERFACE_TUNING = Object.freeze({
  ICON_TINY: 12, ICON_COMPACT: 14, SIGNUP_PASSWORD_MIN: 8,
  ICON_SMALL: 16, ICON_MEDIUM: 17, ICON_ACTION: 18, ICON_MENU: 20,
  ICON_NAV: 22, ICON_STAFF: 29, ICON_SHOP: 36,
  PROJECTION_LEFT_PERCENT: 48, PROJECTION_TOP_PERCENT: 51,
  PROJECTION_HORIZONTAL_PERCENT: 38, PROJECTION_VERTICAL_PERCENT: 17,
  CELL_CENTER: .5, EQUIPMENT_DEPTH_BASE: 10,
  PLATES_WIDTH_PERCENT: 22, BAR_WIDTH_PERCENT: 29, BENCH_WIDTH_PERCENT: 33,
  STATION_MIN_WIDTH_PERCENT: 15, STATION_MAX_WIDTH_PERCENT: 30,
  PREVIEW_MIN_WIDTH_PERCENT: 11, PREVIEW_MIN_HEIGHT_PERCENT: 9,
  PREVIEW_TILE_WIDTH_PERCENT: 6, PREVIEW_TILE_HEIGHT_PERCENT: 4,
  AMBIENT_STEP_INTERVAL_MS: 100, AMBIENT_FRAME_TICKS: 3, FACILITY_REFRESH_MS: 60_000,
});
export const TEXTURE_FORMAT = Object.freeze({
  RGBA_STRIDE: 4, ALPHA_CHANNEL: 3, KEY_RED_MIN: 150, KEY_BLUE_MIN: 75,
  KEY_GREEN_RATIO_MAX: .63, KEY_BLUE_RED_RATIO_MIN: .34,
});
